config/routes.rb
Rails.application.routes.draw do
  get 'pages/landing'

  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'students#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def landing
    @asdasdsad = Student.all
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :age, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecondApp</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="<%= params[:action] == 'students' ? 'active' : '' %>"> <%= link_to "Home", students_path %></li>
            <li class="<%= params[:action] == 'landing' ? 'active' : '' %>"><%= link_to "Landing", pages_landing_path %></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/landing.html.erb
<legend><h1>Estudiantes</h1></legend>
<div class="col-lg-6">
  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>Nº</th>
        <th>Nombre</th>
        <th>Edad</th>
        <th>Correo</th>
        <th>Fecha Creacion</th>
      </tr>
    </thead>
    <tbody>
      <% @asdasdsad.each_with_index do |student, index| %>
      <tr>
        <td><%= index+1 %></td>
        <td><%= student.name %></td>
        <td><%= student.age %></td>
        <td><%= student.email %></td>
        <td><%= student.created_at.strftime("%m/%d/%Y") %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :Nombre %>
    <%= form.text_field :name, id: :student_name %>
  </div>

  <div class="field">
    <%= form.label :Edad %>
    <%= form.number_field :age, id: :student_age %>
  </div>

  <div class="field">
    <%= form.label :Correo %>
    <%= form.text_field :email, id: :student_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <legend>Students</legend>

  <% @students.each do |student| %>
    <div class="col-lg-4">
      <h4><%= student.name %>, <%= student.age %> Años, Correo : <%= student.email %> </h4>
      <ol class="breadcrumb">
        <li><%= link_to 'Ver', student, class:"btn btn-info" %></li>
        <li><%= link_to 'Editar', edit_student_path(student), class:"btn btn-success" %></li>
        <li><%= link_to 'Eliminar', student, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></li>
      </ol>
    </div>
  <% end %>
</div>
<br>

<div class="row">
  <%= link_to 'New', new_student_path, class:"btn btn-info" %>
</div>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @student.age %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>